name: Lint Code

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.x
#
      - name: Install dependencies
        run: |
          pip install pylint

      - name: Lint Python code
        run: |
          pylint processing

      - name: Terraform fmt check
        run: |
          terraform fmt -check --recursive
